version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./server
    working_dir: /app
    volumes:
      - ./server:/app            # код с хоста
      - /app/node_modules        # отдельный volume внутри контейнера для зависимостей
    command: node server.js
    ports:
      - "3000:3000"
    restart: always
